-- =====================================================
-- 1. Create Tables in Staging layer
-- =====================================================
USE DATABASE ORDER_DB;
USE SCHEMA ORDER_DB.RAW;
USE ROLE SYSADMIN;
GRANT CREATE TABLE ON SCHEMA ORDER_DB.RAW TO ROLE SYSADMIN;

CREATE TABLE IF NOT EXISTS STAGING.STG_CUSTOMERS
LIKE RAW.RAW_CUSTOMERS;


CREATE TABLE IF NOT EXISTS STAGING.STG_ORDERS
LIKE RAW.RAW_ORDERS;


CREATE TABLE IF NOT EXISTS STAGING.STG_ORDER_ITEMS
LIKE RAW.RAW_ORDER_ITEMS;
